version: '3.8'
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/staticfiles
    networks:
      - web_network
    depends_on: 
      - appseed-app
  # cache:
  #   image: redis:6.2-alpine
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  #   volumes: 
  #     - cache:/data
# volumes:
#   cache:
#     driver: local
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
    
volumes:
  cache:
    driver: local
  static_volume:
 