# Generated by Django 4.2.4 on 2023-12-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retweets',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.TextField(blank=True, db_column='Datetime', null=True)),
                ('keyword', models.TextField(blank=True, db_column='Keyword', null=True)),
                ('tweet_id', models.IntegerField(blank=True, db_column='Tweet_Id', null=True)),
                ('username', models.TextField(blank=True, db_column='Username', null=True)),
                ('retweeters', models.TextField(blank=True, db_column='Retweeters', null=True)),
                ('sentiment', models.TextField(blank=True, db_column='Sentiment', null=True)),
            ],
            options={
                'db_table': 'retweets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topdaily',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('indexkey', models.TextField(blank=True, null=True)),
                ('retrieved', models.TextField(blank=True, db_column='Retrieved', null=True)),
                ('datetime', models.TextField(blank=True, db_column='Datetime', null=True)),
                ('keyword', models.TextField(blank=True, db_column='Keyword', null=True)),
                ('tweet_id', models.IntegerField(blank=True, db_column='Tweet_Id', null=True)),
                ('username', models.TextField(blank=True, db_column='Username', null=True)),
                ('likes', models.IntegerField(blank=True, db_column='Likes', null=True)),
                ('retweeted', models.IntegerField(blank=True, db_column='Retweeted', null=True)),
                ('text', models.TextField(blank=True, db_column='Text', null=True)),
                ('score', models.FloatField(blank=True, db_column='Score', null=True)),
                ('text_cleaned', models.TextField(blank=True, db_column='Text_cleaned', null=True)),
                ('sentiment', models.TextField(blank=True, db_column='Sentiment', null=True)),
            ],
            options={
                'db_table': 'topdaily',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(blank=True, db_column='Datetime', null=True)),
                ('keyword', models.TextField(blank=True, db_column='Keyword', null=True)),
                ('tweet_id', models.IntegerField(blank=True, db_column='Tweet_Id', null=True)),
                ('username', models.TextField(blank=True, db_column='Username', null=True)),
                ('likes', models.IntegerField(blank=True, db_column='Likes', null=True)),
                ('retweeted', models.IntegerField(blank=True, db_column='Retweeted', null=True)),
                ('text', models.TextField(blank=True, db_column='Text', null=True)),
                ('score', models.FloatField(blank=True, db_column='Score', null=True)),
                ('text_cleaned', models.TextField(blank=True, db_column='Text_cleaned', null=True)),
                ('sentiment', models.TextField(blank=True, db_column='Sentiment', null=True)),
                ('retrieved', models.IntegerField(blank=True, db_column='Retrieved', null=True)),
            ],
            options={
                'db_table': 'tweets',
                'managed': False,
            },
        ),
    ]
